"""P5 deterministic apply worker."""

from __future__ import annotations

import json
import os
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from knowledge_topology.ids import new_id
from knowledge_topology.paths import TopologyPaths
from knowledge_topology.schema.mutation_pack import MutationPack, MutationPackError
from knowledge_topology.schema.loader import load_json
from knowledge_topology.storage.transaction import atomic_write_text


class ApplyError(ValueError):
    """Raised when a mutation pack cannot be applied safely."""


def utc_now() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def check_evidence(paths: TopologyPaths, evidence_refs: list[str]) -> None:
    for ref in evidence_refs:
        prefix = ref.split("_", 1)[0]
        if prefix == "src":
            candidates = [paths.resolve(f"raw/packets/{ref}/packet.json")]
        elif prefix == "dg":
            candidates = list(paths.resolve("digests/by_source").glob(f"*/{ref}.json"))
        else:
            candidates = []
        if not any(candidate.exists() for candidate in candidates):
            raise ApplyError(f"evidence ref does not resolve: {ref}")


def registry_path(paths: TopologyPaths, op: str) -> Path:
    mapping = {
        "create_claim": "canonical/registry/claims.jsonl",
        "add_edge": "canonical/registry/edges.jsonl",
        "open_gap": "ops/gaps/open.jsonl",
        "propose_node": "canonical/registry/nodes.jsonl",
    }
    return paths.resolve(mapping[op])


def page_path(paths: TopologyPaths, change: dict[str, Any]) -> Path | None:
    op = change["op"]
    if op == "create_claim":
        return paths.resolve(f"canonical/nodes/claim/{change['claim_id']}.md")
    if op == "add_edge":
        return paths.resolve(f"canonical/nodes/artifact/{change['edge_id']}.md")
    if op == "propose_node":
        return paths.resolve(f"canonical/nodes/claim/{change['node_id']}.md")
    return None


def record_for_change(change: dict[str, Any], pack: MutationPack) -> dict[str, Any]:
    record = dict(change)
    record["mutation_pack_id"] = pack.id
    record["applied_at"] = utc_now()
    return record


def render_page(change: dict[str, Any], pack: MutationPack) -> str:
    title = change.get("statement") or change.get("note") or change.get("reason") or change["op"]
    return "\n".join([
        "---",
        f"id: {change.get('claim_id') or change.get('edge_id') or change.get('node_id')}",
        f"mutation_pack_id: {pack.id}",
        f"op: {change['op']}",
        "---",
        "",
        f"# {title}",
        "",
        "Generated by deterministic apply. Narrative sections may be expanded later through mutation/apply.",
        "",
    ])


def append_jsonl(path: Path, record: dict[str, Any]) -> None:
    existing = path.read_text(encoding="utf-8") if path.exists() else ""
    atomic_write_text(path, existing + json.dumps(record, sort_keys=True) + "\n")


def write_audit_event(paths: TopologyPaths, pack: MutationPack) -> Path:
    now = datetime.now(timezone.utc)
    event_id = new_id("evt")
    event_dir = paths.ensure_dir(f"ops/events/{now:%Y/%m/%d}")
    event_path = event_dir / f"{event_id}.json"
    payload = {
        "schema_version": "1.0",
        "id": event_id,
        "event_type": "mutation_applied",
        "occurred_at": now.replace(microsecond=0).isoformat().replace("+00:00", "Z"),
        "actor": "apply_worker",
        "summary": f"Applied mutation pack {pack.id}",
        "refs": {"mutation_pack_id": pack.id},
        "canonical_rev": pack.base_canonical_rev,
    }
    atomic_write_text(event_path, json.dumps(payload, indent=2, sort_keys=True) + "\n")
    return event_path


def apply_mutation(
    root: str | Path,
    mutation_path: str | Path,
    *,
    current_canonical_rev: str,
    subject_repo_id: str,
    subject_head_sha: str,
    approve_human: bool = False,
) -> tuple[Path, Path]:
    paths = TopologyPaths.from_root(root)
    mutation = Path(mutation_path)
    pack = MutationPack.from_dict(load_json(mutation))
    if pack.base_canonical_rev != current_canonical_rev:
        raise ApplyError("base_canonical_rev is stale")
    if pack.subject_repo_id != subject_repo_id:
        raise ApplyError("subject_repo_id mismatch")
    if pack.subject_head_sha != subject_head_sha:
        raise ApplyError("subject_head_sha mismatch")
    if pack.requires_human and not approve_human:
        raise ApplyError("human-gated mutation requires approval")
    check_evidence(paths, pack.evidence_refs)

    writes: list[tuple[Path, str]] = []
    registry_records: list[tuple[Path, dict[str, Any]]] = []
    for change in pack.changes:
        record = record_for_change(change, pack)
        registry_records.append((registry_path(paths, change["op"]), record))
        page = page_path(paths, change)
        if page is not None:
            writes.append((page, render_page(change, pack)))

    for path, text in writes:
        atomic_write_text(path, text)
    for path, record in registry_records:
        append_jsonl(path, record)
    event_path = write_audit_event(paths, pack)

    applied_dir = paths.ensure_dir("mutations/applied")
    applied_path = applied_dir / mutation.name
    os.replace(mutation, applied_path)
    return applied_path, event_path
